### ISSUE TITLE
Broken erase?

### ISSUE THREAD

**Issue by cmuramoto** [MnO2/rust-cedar#12]
Hello. I was performing some stress tests on my backport and think that erase_ should test for CEDAR_NO_VALUE before actually deferring the call erase__.

The following panics with index out of bounds:

```rust
fn broken_erase() {
  let mut c = Cedar::new();

  c.update("aa", 0);
  c.update("ab", 1);

  c.erase("a"); // should not have any side effect
  c.erase("aa");
  c.erase("ab"); // panics
}
```

Perhaps

```rust
fn erase_(&mut self, key: &[u8]) {
  let mut from = 0;

  if let Some(value) = self.find(&key, &mut from) {
    if value != CEDAR_NO_VALUE {
      self.erase__(from);
    }
  }
}
```
will do the trick?

**Comment by MnO2** [comment]
Thanks for reporting. I just made the fix: https://github.com/MnO2/cedarwood/commit/f75f545d89d8923929a6c07f29806d7cabf37133

Please update your version to v0.4.5
